##############################################################
# DBMS Connection Info
##############################################################
jdbc.driver=org.postgresql.Driver
jdbc.type=jdbc:postgresql://
#jdbc.url=10.1.73.150
#jdbc.port=6001
jdbc.url=211.250.124.175
jdbc.port=5432
jdbc.sid=xeus-ai-doro
#jdbc.sid=xeus-aplab-dev
jdbc.user=postgres
jdbc.passwd=geomex3280!

##############################################################
# Proxy Target URL
##############################################################
proxy.include=101.102.104.113/172.24.143.199/98.22.24.60
proxy.exclude=222.107.208.134/argos.seocho.go.kr/cctv.seocho.go.kr

##############################################################
# DMZ Proxy Connection URL
##############################################################
#dmz.url=http://127.0.0.1:9090/xeus-map/proxy.jsp?url=
dmz.url=

##############################################################
# GIS Engine Connection URL
##############################################################
engine.url=http://127.0.0.1:2222/
engine.context=xeus

##############################################################
# SHP Options
##############################################################

engine.shp.storage=D:/gis-mng_shp/
engine.shp.db.type=postgis
engine.shp.db.schema=shp

##############################################################
# ETC DBMS Connection Info
##############################################################
jdbc.saenoon.driver=org.postgresql.Driver
jdbc.saenoon.type=jdbc:postgresql://
jdbc.saenoon.url=10.1.73.13
jdbc.saenoon.port=5432
jdbc.saenoon.sid=sanoon_lprdb
jdbc.saenoon.user=postgres
jdbc.saenoon.passwd=geomex12#

##############################################################
# XEUS-GATE Connection Info
##############################################################
gate.url=http://10.1.73.179:8080/xeus-gate/

##############################################################
# System Setting
##############################################################
sys.sms="N"
sys.video.smy="N"

##############################################################
# Tvius Car FTP Connection Info
##############################################################
car.ftp.host="10.1.73.194"
car.ftp.port=21
car.ftp.id="admin"
car.ftp.pw="geomex12#"
car.ftp.basicpath="/lpr"

##############################################################
# Network drive file download
##############################################################
# \ub124\ud2b8\uc6cc\ud06c \ub4dc\ub77c\uc774\ube0c \uc5ec\ubd80
packager.org.netdrive.chk=true
# \ub124\ud2b8\uc6cc\ud06c \ub4dc\ub77c\uc774\ube0c OS IP
packager.org.netdrive.ip=101.102.105.101
# \ub124\ud2b8\uc6cc\ud06c \ub4dc\ub77c\uc774\ube0c OS ID
packager.org.netdrive.id=administrator
# \ub124\ud2b8\uc6cc\ud06c \ub4dc\ub77c\uc774\ube0c OS PW
packager.org.netdrive.pw=2435wret@$#%
# \ub124\ud2b8\uc6cc\ud06c \ub4dc\ub77c\uc774\ube0c \uba85\uce6d
packager.org.netdrive.nm=nas
# \ub124\ud2b8\uc6cc\ud06c \ub4dc\ub77c\uc774\ube0c Root Path (\uc608 - CRMS_ORG_STORAGE \ud3f4\ub354)
packager.org.netdrive.root.path=CRMS_ORG_STORAGE

##############################################################
# \ube44\ub514\uc624\uc368\uba38\ub9ac IP PORT\uc815\ubcf4
##############################################################
video.smy=http://172.16.1.58:16629/

##############################################################
# BACKUP PROCESS TYPE
##############################################################
# \uc7ac\ubc18\ucd9c SDK \uc5ec\ubd80 0(\uc774\ubd80\uc7a5\ub2d8\uc774 \ub9cc\ub4dc\uc2e0\uac70) / 1(\ubcf8\ubd80\uc7a5\ub2d8\uc774 \ub9cc\ub4dc\uc2e0\uac70)
tvius.process="0"


#ai.image.url=http://211.250.124.175:28001/api/v1/files/download?id={id}&kind=box

ai.image.url=http://211.250.124.175:28001/api/v1/files/downloadtest?id={id}&kind=box
